version: "3"

services:
    mysql:
        image: mysql:latest
        restart: always
        container_name: ${CONTAINER_NAME}-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            # Montamos un volumen para MySQL para no perder los datos de bd
            - ./volumenes/mysql:/var/lib/mysql
            - ./config/mysql/config-custom.cnf:/etc/mysql/conf.d/mysql.cnf
        expose:
            - 3306
        networks:
            - internal
        labels:
            - traefik.enable=false

    php56:
        image: chialab/php:5.6-apache
        container_name: ${CONTAINER_NAME}-php56
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
            - ./config/php/php.ini-development:/usr/local/etc/php/php.ini
        links: 
            - mysql
            - mailhog
        labels:
            - traefik.backend=php56
            - traefik.frontend.rule=Host:php56.localhost
            - traefik.docker.network=web
            - traefik.port=80
        networks:
            - internal
            - web

    php70:
        image: chialab/php:7.0-apache
        container_name: ${CONTAINER_NAME}-php70
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
            - ./config/php/php.ini-development:/usr/local/etc/php/php.ini
        links: 
            - mysql
            - mailhog
        labels:
            - traefik.backend=php70
            - traefik.frontend.rule=Host:php70.localhost
            - traefik.docker.network=web
            - traefik.port=80
        networks:
            - internal
            - web

    php72:
        image: chialab/php:7.2-apache
        container_name: ${CONTAINER_NAME}-php72
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
            - ./config/php/php.ini-development:/usr/local/etc/php/php.ini
        links: 
            - mysql
            - mailhog
        labels:
            - traefik.backend=php72
            - traefik.frontend.rule=Host:php72.localhost
            - traefik.docker.network=web
            - traefik.port=80
        networks:
            - internal
            - web

    php74:
        image: chialab/php:7.4-apache
        container_name: ${CONTAINER_NAME}-php74
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
            - ./config/php/php.ini-development:/usr/local/etc/php/php.ini
        links: 
            - mysql
            # - mailhog
        labels:
            - traefik.backend=php74
            - traefik.frontend.rule=Host:php74.localhost
            - traefik.docker.network=web
            - traefik.port=80
        networks:
            - internal
            - web

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${CONTAINER_NAME}-phpmyadmin
        restart: always
        volumes:
            - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            PMA_HOSTS: mysql
            UPLOAD_LIMIT: 100M
        depends_on:
            - mysql
        links:
            - mysql
        labels:
            - traefik.backend=phpmyadmin
            - traefik.frontend.rule=Host:phpmyadmin.localhost
            - traefik.docker.network=web
            - traefik.port=80
        networks:
            - internal
            - web

    mailhog:
        image: mailhog/mailhog:latest 
        container_name: ${CONTAINER_NAME}-mailhog
        restart: always
        labels:
            - traefik.backend=mailhog
            - traefik.frontend.rule=Host:mailhog.localhost
            - traefik.docker.network=web
            - traefik.port=8025
        networks:
            - internal
            - web

    mongo:
        image: mongo
        container_name: ${CONTAINER_NAME}-mongo
        restart: always
        volumes:
            - ./volumenes/mongodb:/data/db
        networks:
            - internal
        labels:
            - traefik.enable=false

    traefik:
        restart: always
        image: traefik:1.7.2-alpine
        container_name: dammp-traefik
        ports:
            - 80:80
            - 443:443
            - 8080:8080 #The web UI (enabled by --api)
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config/traefik/traefik.toml:/traefik.toml
            - ./config/traefik/acme.json:/acme.json
        networks:
            - web
        labels:
            - traefik.frontend.rule=Host:monitor.localhost
            - traefik.port=8080


networks:
    internal:
        external: false
    web:
        external: true