version: "3"

services:
    mysql:
        image: mysql:latest
        restart: always
        container_name: ${CONTAINER_NAME}-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            # Montamos un volumen para MySQL para no perder los datos de bd
            - ./volumenes/mysql:/var/lib/mysql
        expose:
            - 3306

    php56:
        image: chialab/php:5.6-apache
        container_name: ${CONTAINER_NAME}-php56
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
        expose:
            - 8080
        ports:
            - 8056:80
        links: 
            - mysql
            - mailhog

    php70:
        image: chialab/php:7.0-apache
        container_name: ${CONTAINER_NAME}-php70
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
        expose:
            - 8080
        ports:
            - 8070:80
        links: 
            - mysql
            - mailhog

    php72:
        image: chialab/php:7.2-apache
        container_name: ${CONTAINER_NAME}-php72
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
        expose:
            - 8080
        ports:
            - 8072:80
        links: 
            - mysql
            - mailhog

    php74:
        image: chialab/php:7.4-apache
        container_name: ${CONTAINER_NAME}-php74
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
        expose:
            - 8080
        ports:
            - 8074:80
        links: 
            - mysql
            - mailhog

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${CONTAINER_NAME}-phpmyadmin
        restart: always
        ports: 
            - "${PHPMYADMIN_PORT}:80"
        volumes:
            - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            PMA_HOSTS: mysql
            UPLOAD_LIMIT: 100M
        depends_on:
            - mysql
        links:
            - mysql

    mailhog:
        image: mailhog/mailhog:latest 
        container_name: ${CONTAINER_NAME}-mailhog
        restart: always
        ports:
            - "${MAILHOG_PORT}:8025"

    mongo:
        image: mongo
        container_name: ${CONTAINER_NAME}-mongo
        restart: always
        volumes:
            - ./volumenes/mongodb:/data/db        
        ports:
            - ${MONGO_PORT}:27017
            
