version: "3.9"

services:
    mysql:
        image: mysql:latest
        # restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
        # Montamos un volumen para MySQL para no perder los datos de bd
            - ./volumenes/mysql:/var/lib/mysql
        expose:
            - 3306

    # php70:
    #     image: chialab/php:7.0-apache
    #     container_name: apache-php70
    #     volumes:
    #         # Montamos nuestra web desde fuera en el directorio web del contenedor
    #         - ./htdocs:/var/www/html
    #     expose:
    #         - 8080
    #     ports:
    #         - 8070:80
    #     links: 
    #         - mysql

    php74:
        image: chialab/php:7.4-apache
        container_name: apache-php74
        #command: python manage.py runserver 0.0.0.0:8000
        #command: chown -R www-data:www-data /var/www
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
        expose:
            - 8080
        ports:
            - 8074:80
        links: 
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        # restart: always
        # container_name: phpmyadmin
        ports: 
            - "${PHPMYADMIN_PORT}:80"
        volumes:
            - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            PMA_HOSTS: mysql
            UPLOAD_LIMIT: 100M
        depends_on:
            - mysql
        links:
            - mysql
            
