version: "3"

services:
    mysql:
        #platform: linux/x86_64
        image: mysql:latest
        restart: always
        container_name: ${CONTAINER_NAME}-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            # Montamos un volumen para MySQL para no perder los datos de bd
            - ./volumenes/mysql:/var/lib/mysql
            - ./config/mysql/config-custom.cnf:/etc/mysql/conf.d/mysql.cnf
        expose:
            - 3306
        networks:
            - internal

    php56:
        #platform: linux/x86_64
        image: chialab/php:5.6-apache
        container_name: ${CONTAINER_NAME}-php56
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
            - ./config/php/php.ini-development:/usr/local/etc/php/php.ini
        links: 
            - mysql
            - mailhog
        networks:
            - internal
        ports:
            - 8056:80

    php70:
        #platform: linux/x86_64
        image: chialab/php:7.0-apache
        container_name: ${CONTAINER_NAME}-php70
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
            - ./config/php/php.ini-development:/usr/local/etc/php/php.ini
        links: 
            - mysql
            - mailhog
        networks:
            - internal
        ports:
            - 8070:80

    php72:
        #platform: linux/x86_64
        image: chialab/php:7.2-apache
        container_name: ${CONTAINER_NAME}-php72
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
            - ./config/php/php.ini-development:/usr/local/etc/php/php.ini
        links: 
            - mysql
            - mailhog
        networks:
            - internal
        ports:
            - 8072:80

    php74:
        #platform: linux/x86_64
        image: chialab/php:7.4-apache
        container_name: ${CONTAINER_NAME}-php74
        restart: always
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./htdocs:/var/www/html
            - ./config/php/php.ini-development:/usr/local/etc/php/php.ini
        links: 
            - mysql
            - mailhog
        networks:
            - internal
        ports:
            - 8074:80

    phpmyadmin:
        #platform: linux/x86_64
        image: phpmyadmin/phpmyadmin
        container_name: ${CONTAINER_NAME}-phpmyadmin
        restart: always
        volumes:
            - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            PMA_HOSTS: mysql
            UPLOAD_LIMIT: 100M
        depends_on:
            - mysql
        links:
            - mysql
        ports:
            - 8001:80
        networks:
            - internal

    mailhog:
        #platform: linux/x86_64
        image: mailhog/mailhog:latest 
        container_name: ${CONTAINER_NAME}-mailhog
        restart: always
        networks:
            - internal

    mongo:
        #platform: linux/x86_64
        image: mongo
        container_name: ${CONTAINER_NAME}-mongo
        restart: always
        volumes:
            - ./volumenes/mongodb:/data/db
        networks:
            - internal

networks:
    internal:
        external: false
