defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$ymqgEL8c$Ts6GTSvFUzCALu6okX9WA/"] #dammpadmin
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[api]
  entrypoint="dashboard"

[acme]
  email = "favio@syloper.com"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
    [acme.httpChallenge]
    entryPoint = "http"

[docker]
  domain = "localhost"
  watch = true
  network = "web"